export const routes = {
  login: "auth/login",
  logout: "auth/logout",
  register: "auth/register",
  dashboard: "/dashboard",
  reservations: "/reservations",
  reservationsPending: '/admin/reservations',
  spaces: "/spaces",
  registerFront: "/registrar",  
  reservationsFront: "/reservas",
  reservationsAdminFront: "/reservas-pendientes",
  reservationsCrearFront: "/reservas/crear",
  spacesFront: "/espacios",
  getUser: "/user",
};
